### ISSUE TITLE
scan_user fails when clone_repo fails

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#183]
`scan_user` may break when some repository can't be cloned

Example:
```
INFO:credentialdigger.client:1/n) Scanning https://api.github.com/repos/USER/REPO
DEBUG:credentialdigger.client:Start scan
DEBUG:credentialdigger.scanners.git_scanner:Authenticate user with token
Traceback (most recent call last):
...
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/cli/scan_user.py", line 103, in run
    discoveries = client.scan_user(
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/client.py", line 982, in scan_user
    missing_ids[repo_url] = self._scan(repo_url, scanner,
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/client.py", line 1096, in _scan
    raise e
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/client.py", line 1088, in _scan
    new_discoveries = scanner.scan(repo_url,
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/scanners/git_scanner.py", line 143, in scan
    project_path, repo = self.get_git_repo(repo_url, local_repo)
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/scanners/git_scanner.py", line 104, in get_git_repo
    raise e
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.0.4-py3.9.egg/credentialdigger/scanners/git_scanner.py", line 100, in get_git_repo
    GitRepo.clone_from(repo_url, project_path)
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 1032, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/repo/base.py", line 973, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.9/site-packages/git/util.py", line 329, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://XXXXXXX@github.com/USER/REPO /var/folders/7t/...
  stderr: 'Cloning into '/var/folders/7t/...'...
remote: Access to this repository has been disabled by GitHub staff.
remote: If you are the repository owner, you can contact support via
remote: https://support.github.com/contact for more information.
fatal: unable to access 'https://github.com/USER/REPO/': The requested URL returned error: 403
'
```

**Comment by marcorosa** [comment]
Fix released in #228
