### ISSUE TITLE
broken symbolic links break scan

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#200]
When scanning a repo which contains a symlink for a file, the scanner breaks because it cannot open it.

```
Exception in thread credentialdigger@https://github.com/chrispcx/es-hhvm:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/client.py", line 841, in scan_snapshot
    return self._scan(
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/client.py", line 1077, in _scan
    raise e
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/client.py", line 1069, in _scan
    new_discoveries = scanner.scan(repo_url,
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/scanners/git_file_scanner.py", line 98, in scan
    discoveries = self._scan(
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/scanners/git_file_scanner.py", line 152, in _scan
    file_discoveries = self.scan_file(
  File "/Users/i355397/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.2.0-py3.9.egg/credentialdigger/scanners/file_scanner.py", line 156, in scan_file
    with open(full_path, 'r', encoding='utf-8') as file_to_scan:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/7t/3qnrz9cj0ml8zsb_fw1wk4t40000gn/T/tmpjy6qwjnf/glog/google-glog-0.3.4/test-driver'
```

**Comment by marcorosa** [comment]
Fix released in #228
