### ISSUE TITLE
OSError during compute_embeddings 

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#220]
In rare occasions, when `compute_embeddings` is called at the end of a scan, a crash happens:

```
INFO:credentialdigger.client:Compute embeddings for this repository
INFO:absl:Using /var/folders/7t/3qnrz9cj0ml8zsb_fw1wk4t40000gn/T/tfhub_modules to cache modules.
Exception in thread credentialdigger@https://github.com/USER/REPO:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/client.py", line 795, in scan
    return self._scan(
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/client.py", line 1184, in _scan
    self.add_embeddings(repo_url)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/client_sqlite.py", line 222, in add_embeddings
    super().add_embeddings(query, repo_url)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/client.py", line 175, in add_embeddings
    embeddings] = self.compute_repo_embeddings(repo_url)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/client.py", line 1287, in compute_repo_embeddings
    similarity_model = build_embedding_model()
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/credentialdigger-4.5.1-py3.9.egg/credentialdigger/snippet_similarity.py", line 33, in build_embedding_model
    preprocessing_layer = hub.KerasLayer(tfhub_preprocessing,
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 153, in __init__
    self._func = load_module(handle, tags, self._load_options)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow_hub/keras_layer.py", line 449, in load_module
    return module_v2.load(handle, tags=tags, options=set_load_options)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow_hub/module_v2.py", line 106, in load
    obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow/python/saved_model/load.py", line 878, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "/Users/marco/git/credential-digger/venv/lib/python3.9/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /var/folders/7t/3qnrz9cj0ml8zsb_fw1wk4t40000gn/T/tfhub_modules/602d30248ff7929470db09f7385fc895e9ceb4c0/{saved_model.pbtxt|saved_model.pb}
```

**Comment by marcorosa** [comment]
Related resources:
- https://stackoverflow.com/questions/63078695/savedmodel-file-does-not-exist-when-using-tensorflow-hub
- https://github.com/tensorflow/hub/issues/575
