### ISSUE TITLE
hyperscan.error: Pattern is too large.

### ISSUE THREAD

**Issue by Deathpoolxrs** [SAP/credential-digger#310]
We are using the following regex to scan the local repo but we are getting hyperscan.error: Pattern is too large error. Could please resolve this issue?

**Regex we used:**
https://github.com/h33tlit/secret-regex-list

**Note:** We used all regexes of the above repo

**Error Details:**
```
INFO:credentialdigger.cli.cli:Database in use: Sqlite
Traceback (most recent call last):
  File "/usr/local/bin/credentialdigger", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/__main__.py", line 7, in main
    cli.main(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/cli/cli.py", line 152, in main
    args.func(client, args)
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/cli/scan_path.py", line 98, in run
    discoveries = client.scan_path(
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/client.py", line 916, in scan_path
    scanner = FileScanner(rules)
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/scanners/file_scanner.py", line 28, in __init__
    self.stream = rules
  File "/usr/local/lib/python3.10/site-packages/credentialdigger/scanners/file_scanner.py", line 48, in stream
    self._stream.compile(expressions=expressions,
hyperscan.error: Pattern is too large.
```

**Comment by marcorosa** [comment]
Hello, I investigated a bit in this issue and it seems related to `hyperscan`, that is one of the dependencies of `credentialdigger`.
In particular, there seems to be a regex that cannot be compiled (probably, it's too long):
`"Password in URL": "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]",`

I also tried to shuffle the order of your regexes, and every time it was this specific one that raised that issue.

I am not aware if hyperscan has a limitation on the length of the strings it can match, or on the length of the pattern it can compile.

I made some tests, you can refer to the code below as an example.

### How to replicate

```
import hyperscan
import random

regexes = {
    "Firebase URL": ".*firebaseio\.com",
    "Slack Token": "(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
    "RSA private key": "-----BEGIN RSA PRIVATE KEY-----",
    "SSH (DSA) private key": "-----BEGIN DSA PRIVATE KEY-----",
    ...
    "Password in URL": "[a-zA-Z]{3,10}://[^/\\s:@]{3,20}:[^/\\s:@]{3,20}@.{1,100}[\"'\\s]",
    ...
}
# Extract only the regexes
rules = list(regexes.values())

# Uncomment this instruction if you don't want to raise the exception
# rules.pop(29)
# Password in URL is regex number 29 in your list

# Translate regexes into hyperscan patterns
patterns = []
for rule_id, rule in enumerate(rules):
    patterns_set.append((
        rule.encode('utf-8'), 
        rule_id,
        hyperscan.HS_FLAG_CASELESS |
        hyperscan.HS_FLAG_UTF8 |
        hyperscan.HS_FLAG_UCP))
 
# Uncomment to shuffle patterns order
# random.shuffle(patterns)
# Get features to compile
expressions, ids, flags = zip(*patterns)

stream = hyperscan.Database(mode=hyperscan.HS_MODE_BLOCK)

# If you don't shuffle the patterns (and you don't remove regex No.29), you should raise an exception at regex 30
# If you shuffle the patterns, you raise the exception after the password-in-url regex is compiled
for i in range(1, len(patterns)):
    print({i})
    print(expressions[i])
    stream.compile(
        expressions=expressions[:I],
        ids=ids[:i],
        elements=i,
        flags=flags[:i])
```
