### ISSUE TITLE
Fix empty repo scan exception

### ISSUE THREAD

**Issue by marcorosa** [SAP/credential-digger#62]
The scan of an empty repository raises an exception

```
Traceback (most recent call last):                                                                                                                        [0/1871]
  File "/home/marco/venv/lib/python3.6/site-packages/credentialdigger/client.py", line 752, in scan_user
    debug=debug)
  File "/home/marco/venv/lib/python3.6/site-packages/credentialdigger/client.py", line 591, in scan
    since_commit=from_commit)
  File "/home/marco/venv/lib/python3.6/site-packages/credentialdigger/scanners/git_scanner.py", line 71, in scan
    latest_commit = repo.rev_parse('HEAD').hexsha
  File "/home/marco/venv/lib/python3.6/site-packages/git/repo/fun.py", line 336, in rev_parse
    obj = name_to_object(repo, rev)
  File "/home/marco/venv/lib/python3.6/site-packages/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'HEAD' did not resolve to an object
```

**Comment by marcorosa** [comment]
closed by mistake. Reopen and WIP

**Comment by marcorosa** [comment]
Fixed in `develop`. Will be merged soon into `main` branch

**Comment by marcorosa** [comment]
merged into main. I close the issue.
