### ISSUE TITLE
error: "model path_model is missing meta.json file"

### ISSUE THREAD

**Issue by flowchartsman** [SAP/credential-digger#92]
Built a little play example with the following dockerfile, based on the one in `/ui`:
```dockerfile
FROM python:3.7

RUN pip install Flask python-dotenv
RUN apt-get update && apt-get install -y libhyperscan5 libpq-dev

# Don't verify ssl for github enterprise
RUN git config --global http.sslverify false

# Install Credential Digger
RUN pip install credentialdigger

COPY rules.yml /creddig/rules.yml

WORKDIR /creddig

RUN python -m credentialdigger add_rules --sqlite creddig.db rules.yml

ENV path_model=https://github.com/SAP/credential-digger/releases/download/PM-v1.0.1/path_model-1.0.1.tar.gz
ENV snippet_model=https://github.com/SAP/credential-digger/releases/download/SM-v1.0.0/snippet_model-1.0.0.tar.gz

RUN python -m credentialdigger download path_model && \
    python -m credentialdigger download snippet_model

```

then:
```
$ docker build -t creddigger .
$ docker run --rm -it --entrypoint /bin/bash creddigger
# python -m credentialdigger scan https://github.com/some/repo --sqlite ./creddig.db --models PathModel SnippetModel
INFO:dotenv.main:Python-dotenv could not find configuration file .env.
INFO:credentialdigger.cli.cli:Database in use: Sqlite
INFO:credentialdigger.client:Detected 240 discoveries.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/__main__.py", line 4, in <module>
    cli.main()
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/cli/cli.py", line 114, in main
    args.func(client, args)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/cli/scan.py", line 108, in run
    git_token=args.git_token)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/client.py", line 676, in scan
    mm = ModelManager(model)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/models/model_manager.py", line 33, in __init__
    self.model = this_model(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/models/path_model/path_model.py", line 21, in __init__
    super().__init__(super().find_model_file(model, binary))
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/models/base_model.py", line 95, in find_model_file
    model_meta = self.get_model_meta(model_path)
  File "/usr/local/lib/python3.7/site-packages/credentialdigger/models/base_model.py", line 52, in get_model_meta
    'Contact maintainers' % model_path.name)
FileNotFoundError: It seems that model path_model is  missing meta.json file.Contact maintainers
```

Am I doing something wrong here?

**Comment by flowchartsman** [comment]
Looks as if my failure may have been not specifying `--dotenv`. I did copy a `.env` file into my `/workdir` first to test, but it looks as if it must be specified explicitly. Don't know if that's issue-worthy, so I'll leave it open for now and will close if this is working as intended.

**Comment by marcorosa** [comment]
Hi @flowchartsman, thank you for your very clear report. I followed your steps, and I noticed the following error during the build, happening for both the path and snippet models:

```
Collecting https://github.com/SAP/credential-digger/releases/download/PM-v1.0.1/path_model-1.0.1.tar.gz
  Downloading https://github.com/SAP/credential-digger/releases/download/PM-v1.0.1/path_model-1.0.1.tar.gz (465 kB)
Requirement already satisfied: credentialdigger>=1.0.0 in /usr/local/lib/python3.7/site-packages (from path-model==1.0.1) (3.0.4)
Requirement already satisfied: GitPython in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (3.1.14)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (1.2.3)
Requirement already satisfied: python-string-utils in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (1.0.0)
Requirement already satisfied: PyGithub in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (1.54.1)
Requirement already satisfied: fasttext in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (0.9.2)
Requirement already satisfied: hyperscan==0.1.5 in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (0.1.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (2.25.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (1.20.1)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (2.8.6)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (0.15.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (5.4.1)
Requirement already satisfied: leven in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (1.0.4)
Requirement already satisfied: srsly in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (2.4.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (0.24.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/site-packages (from credentialdigger>=1.0.0->path-model==1.0.1) (4.59.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/site-packages (from GitPython->credentialdigger>=1.0.0->path-model==1.0.1) (4.0.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/site-packages (from pandas->credentialdigger>=1.0.0->path-model==1.0.1) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/site-packages (from pandas->credentialdigger>=1.0.0->path-model==1.0.1) (2.8.1)
Requirement already satisfied: pyjwt<2.0 in /usr/local/lib/python3.7/site-packages (from PyGithub->credentialdigger>=1.0.0->path-model==1.0.1) (1.7.1)
Requirement already satisfied: deprecated in /usr/local/lib/python3.7/site-packages (from PyGithub->credentialdigger>=1.0.0->path-model==1.0.1) (1.2.11)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.7/site-packages (from fasttext->credentialdigger>=1.0.0->path-model==1.0.1) (2.6.2)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.7/site-packages (from fasttext->credentialdigger>=1.0.0->path-model==1.0.1) (46.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->credentialdigger>=1.0.0->path-model==1.0.1) (1.26.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->credentialdigger>=1.0.0->path-model==1.0.1) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->credentialdigger>=1.0.0->path-model==1.0.1) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->credentialdigger>=1.0.0->path-model==1.0.1) (4.0.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/site-packages (from nltk->credentialdigger>=1.0.0->path-model==1.0.1) (7.1.2)
Requirement already satisfied: regex in /usr/local/lib/python3.7/site-packages (from nltk->credentialdigger>=1.0.0->path-model==1.0.1) (2020.11.13)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/site-packages (from nltk->credentialdigger>=1.0.0->path-model==1.0.1) (1.0.1)
Requirement already satisfied: nose in /usr/local/lib/python3.7/site-packages (from leven->credentialdigger>=1.0.0->path-model==1.0.1) (1.3.7)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from leven->credentialdigger>=1.0.0->path-model==1.0.1) (1.15.0)
Requirement already satisfied: catalogue<2.1.0,>=2.0.1 in /usr/local/lib/python3.7/site-packages (from srsly->credentialdigger>=1.0.0->path-model==1.0.1) (2.0.1)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/site-packages (from scikit-learn->credentialdigger>=1.0.0->path-model==1.0.1) (1.6.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/site-packages (from scikit-learn->credentialdigger>=1.0.0->path-model==1.0.1) (2.1.0)
Requirement already satisfied: smmap<4,>=3.0.1 in /usr/local/lib/python3.7/site-packages (from gitdb<5,>=4.0.1->GitPython->credentialdigger>=1.0.0->path-model==1.0.1) (3.0.5)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/site-packages (from deprecated->PyGithub->credentialdigger>=1.0.0->path-model==1.0.1) (1.12.1)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from catalogue<2.1.0,>=2.0.1->srsly->credentialdigger>=1.0.0->path-model==1.0.1) (3.7.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<2.1.0,>=2.0.1->srsly->credentialdigger>=1.0.0->path-model==1.0.1) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < "3.8"->catalogue<2.1.0,>=2.0.1->srsly->credentialdigger>=1.0.0->path-model==1.0.1) (3.7.4.3)
Building wheels for collected packages: path-model
  Building wheel for path-model (setup.py): started
  Building wheel for path-model (setup.py): finished with status 'done'
  Created wheel for path-model: filename=path_model-1.0.1-py3-none-any.whl size=465999 sha256=19b629095e163a5324f93b0e2fe8d707b327defdab2ec3eaf2adb3553515cbe5
  Stored in directory: /tmp/pip-ephem-wheel-cache-r4djtcor/wheels/cc/bb/40/169f8cd436a70da8e1cd66f7ecb4e4e203a218d60b46a413b4
Successfully built path-model
Installing collected packages: path-model
Successfully installed path-model-1.0.1
WARNING: You are using pip version 20.1; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
INFO:credentialdigger.cli.download:Download successful
WARNING:credentialdigger.cli.download:Can not overwrite symlink path_model
This can happen if your data directory contains a directory or file of the same name.
ERROR:credentialdigger.cli.download:Could not link model to path_modelCreating a symlink in `credentialdigger/models_data` failed. Make sure you have the required permissions and try re-running the command as admin, or use a virtualenv. You can still create the symlink manually.
ERROR:credentialdigger.cli.download:/usr/local/lib/python3.7/site-packages/path_model --> /usr/local/lib/python3.7/site-packages/credentialdigger/models_data/path_model
ERROR:credentialdigger.cli.download:Download successful but linking failed
Creating a shortcut link for path_model did not work (maybe you do not have admin permissions?)
```

Context:
When models are downloaded, they are installed as python packages, and then a symlink is created into `credentialdigger/models_data` folder. We followed this approach because it is the same of spacy. 

This error is due to the symlink not being created (I logged into the container and I verified this).
I will investigate further, this seems to be a bug related to our download function [here](https://github.com/SAP/credential-digger/blob/main/credentialdigger/cli/download.py#L88-L106).

**Comment by marcorosa** [comment]
I should have fixed the bug and I've made a new release.

I'm closing this issue, but feel free to reopen it if you experience the same bug (or if you have comments/suggestions)
